packages:
  - 'packages/*'
  - 'apps/*'
  - 'tools/*'

# 排除某些目录
exclude:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/.next/**'

# 共享依赖配置
shared-workspace-lockfile: true
link-workspace-packages: true
prefer-workspace-packages: true

# 安装配置
hoist-pattern:
  - '@types/*'
  - 'eslint*'
  - 'prettier*'
  - 'typescript'
  - 'tsup'
  - 'turbo'

# 公共依赖提升
public-hoist-pattern:
  - '*'

ignoredBuiltDependencies:
  - contentlayer
  - protobufjs
