packages:
  - packages/*
  - apps/*
  - tools/*

exclude:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/.next/**'

hoist-pattern:
  - '@types/*'
  - eslint*
  - prettier*
  - typescript
  - tsup
  - turbo

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - contentlayer
  - core-js-pure
  - esbuild
  - node
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver

link-workspace-packages: true

prefer-workspace-packages: true

public-hoist-pattern:
  - '*'

shared-workspace-lockfile: true
