'use client'
import * as React from 'react'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { Trash2, Pencil } from 'lucide-react'
import * as dictionaryActions from '@/repository/dictionary'
import { DataDictItem } from '@/types/datasource-schema'
import { Card } from '@/components/ui/card'
import MainLayout from '../../app/layouts/main-layout'
import DataDictEditDialog from './data-dict-edit-dialog'
import ConfirmDeleteDialog from '@/components/confirm-delete-dialog'
import { useTranslations } from 'next-intl'

export type DataDict = {
  id: string // database id, auto generated by prisma
  name: string
  items: DataDictItem[]
}

export default function DataDict() {
  const [dicts, setDicts] = useState<DataDict[]>([])
  const [editDialogOpen, setEditDialogOpen] = useState(false)
  const [editDraft, setEditDraft] = useState<DataDict>({ id: '', name: '', items: [] })
  const [editIdx, setEditIdx] = useState<number | null>(null)
  const [loading, setLoading] = useState(false)
  const [deleteIdx, setDeleteIdx] = useState<number | null>(null)
  const t = useTranslations('DataDict')
  const tCommon = useTranslations('Common')

  React.useEffect(() => {
    setLoading(true)
    dictionaryActions
      .getDictionaries()
      .then((data) => {
        setDicts(
          data.map((dict: any) => ({
            ...dict,
            items: Array.isArray(dict.items) ? dict.items : [],
          }))
        )
      })
      .finally(() => setLoading(false))
  }, [])

  const openEdit = (idx?: number) => {
    if (typeof idx === 'number') {
      setEditIdx(idx)
      setEditDraft({ ...dicts[idx], items: [...dicts[idx].items] })
    } else {
      setEditIdx(null)
      setEditDraft({ id: '', name: '', items: [] })
    }
    setEditDialogOpen(true)
  }

  const saveDict = async () => {
    setLoading(true)
    try {
      if (editIdx === null) {
        await dictionaryActions.createDictionary(editDraft.name, editDraft.items)
      } else {
        await dictionaryActions.updateDictionary(editDraft.id, editDraft.name, editDraft.items)
      }
      const data = await dictionaryActions.getDictionaries()
      setDicts(
        data.map((dict: any) => ({
          ...dict,
          items: Array.isArray(dict.items) ? dict.items : [],
        }))
      )
      setEditDialogOpen(false)
      setEditIdx(null)
      setEditDraft({ id: '', name: '', items: [] })
    } finally {
      setLoading(false)
    }
  }

  const deleteDict = async (idx: number) => {
    setLoading(true)
    try {
      await dictionaryActions.deleteDictionary(dicts[idx].id)
      const data = await dictionaryActions.getDictionaries()
      setDicts(
        data.map((dict: any) => ({
          ...dict,
          items: Array.isArray(dict.items) ? dict.items : [],
        }))
      )
      setDeleteIdx(null)
    } finally {
      setLoading(false)
    }
  }

  return (
    <Card className="p-0 w-full md:w-[440px] max-w-full shadow-sm rounded-md ">
      <div className="flex justify-between items-center mb-4 p-6 pb-0">
        <h1 className="text-lg font-semibold">{t('title')}</h1>
        <Button onClick={() => openEdit()}>{tCommon('add')}</Button>
      </div>
      <div className="p-6 pt-0">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>{tCommon('name')}</TableHead>
              <TableHead>{t('items')}</TableHead>
              <TableHead className="text-right">{tCommon('actions')}</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {dicts.map((dict, idx) => (
              <TableRow key={dict.id}>
                <TableCell>{dict.name}</TableCell>
                <TableCell>{t('itemsCount', { count: dict.items?.length ?? 0 })}</TableCell>
                <TableCell className="text-right">
                  <div className="flex gap-2 justify-end">
                    <Button size="sm" variant="outline" onClick={() => openEdit(idx)}>
                      <Pencil className="w-4 h-4" />
                      <span className="sr-only">{tCommon('edit')}</span>
                    </Button>
                    <Button size="sm" variant="destructive" onClick={() => setDeleteIdx(idx)}>
                      <Trash2 className="w-4 h-4" />
                      <span className="sr-only">{tCommon('delete')}</span>
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
      <DataDictEditDialog
        open={editDialogOpen}
        onOpenChange={setEditDialogOpen}
        editDraft={editDraft}
        setEditDraft={setEditDraft}
        editIdx={editIdx}
        loading={loading}
        onSave={saveDict}
        tCommon={tCommon}
      />
      <ConfirmDeleteDialog
        open={deleteIdx !== null}
        setOpen={(open) => !open && setDeleteIdx(null)}
        loading={loading}
        onConfirm={() => deleteIdx !== null && deleteDict(deleteIdx)}
        title={tCommon('delete')}
        description={t('deleteConfirm')}
        confirmText={tCommon('delete')}
        cancelText={tCommon('cancel')}
      />
    </Card>
  )
}
