import type { Metadata } from 'next'
import '../globals.css'
import { hasLocale, NextIntlClientProvider } from 'next-intl'
import { routing } from '@/i18n/routing'
import { notFound } from 'next/navigation'
import React from 'react'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { zhCN, enUS } from '@clerk/localizations'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const { locale } = await params
  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }
  const clerkLocalization = locale === 'zh' ? zhCN : enUS
  return (
    <ClerkProvider localization={clerkLocalization} afterSignOutUrl={`/${locale}/sign-in`}>
      <html lang={locale}>
        <body className={`antialiased`}>
          <NextIntlClientProvider locale={locale}>{children}</NextIntlClientProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
