import type { Metadata } from 'next'
import '../globals.css'
import { hasLocale, NextIntlClientProvider, useMessages } from 'next-intl'
import MainLayout from '../layouts/main-layout'
import { routing } from '@/i18n/routing'
import { notFound } from 'next/navigation'
import React from 'react'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  // Dynamically import messages for the current locale
  return (
    <html lang={locale}>
      <body className={`antialiased`}>
        <NextIntlClientProvider locale={locale}>
          <MainLayout>{children}</MainLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
