name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  # 依赖图分析
  analyze:
    name: Analyze Dependencies
    runs-on: ubuntu-latest
    outputs:
      build-order: ${{ steps.deps.outputs.build-order }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Analyze dependencies
        id: deps
        run: |
          bun scripts/dev/deps-graph.ts > deps-analysis.txt
          echo "build-order=[]" >> $GITHUB_OUTPUT

      - name: Upload analysis
        uses: actions/upload-artifact@v4
        with:
          name: dependency-analysis
          path: deps-analysis.txt

  # 核心验证
  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: [analyze]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run full validation
        run: bun run validate

  # 安全检查
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Security audit
        run: bun audit --audit-level moderate

      - name: Check for vulnerabilities
        run: |
          if bun audit --audit-level high --json | jq '.vulnerabilities | length' | grep -v '^0$'; then
            echo "High severity vulnerabilities found"
            exit 1
          fi
