name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  # 依赖图分析
  analyze:
    name: Analyze Dependencies
    runs-on: ubuntu-latest
    outputs:
      build-order: ${{ steps.deps.outputs.build-order }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Analyze dependencies
        id: deps
        run: |
          node scripts/deps-graph.js > deps-analysis.txt
          echo "build-order=[]" >> $GITHUB_OUTPUT

      - name: Upload analysis
        uses: actions/upload-artifact@v4
        with:
          name: dependency-analysis
          path: deps-analysis.txt

  # 代码质量检查
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run turbo lint

      - name: Format check
        run: bun run turbo format

      - name: Type check
        run: bun run turbo check-types

  # 构建和测试
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [analyze]
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build packages
        run: bun run turbo build:packages

      - name: Test
        run: bun run turbo test

      - name: Upload coverage
        if: matrix.node-version == 20
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage

  # 构建应用
  build-apps:
    name: Build Apps
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build apps
        run: bun run turbo build --filter='./apps/*'

  # 安全检查
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Security audit
        run: bun audit --audit-level moderate

      - name: Check for vulnerabilities
        run: |
          if bun audit --audit-level high --json | jq '.vulnerabilities | length' | grep -v '^0$'; then
            echo "High severity vulnerabilities found"
            exit 1
          fi
