'use client'
import * as React from 'react'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog'
import { Trash2 } from 'lucide-react'
import * as dictionaryActions from '@/repository/dictionary'
import { DataDictItem } from '@/types/datasource-schema'
import { Card } from '@/components/ui/card'
import MainLayout from '../../../layouts/main-layout'

export type DataDict = {
  id: string // database id, auto generated by prisma
  name: string
  items: DataDictItem[]
}

export default function DataDictPage() {
  const [dicts, setDicts] = useState<DataDict[]>([])
  const [editDialogOpen, setEditDialogOpen] = useState(false)
  const [editDraft, setEditDraft] = useState<DataDict>({ id: '', name: '', items: [] })
  const [editIdx, setEditIdx] = useState<number | null>(null)
  const [loading, setLoading] = useState(false)

  React.useEffect(() => {
    setLoading(true)
    dictionaryActions
      .getDictionaries()
      .then((data) => {
        setDicts(
          data.map((dict: any) => ({
            ...dict,
            items: Array.isArray(dict.items) ? dict.items : [],
          }))
        )
      })
      .finally(() => setLoading(false))
  }, [])

  const openEdit = (idx?: number) => {
    if (typeof idx === 'number') {
      setEditIdx(idx)
      setEditDraft({ ...dicts[idx], items: [...dicts[idx].items] })
    } else {
      setEditIdx(null)
      setEditDraft({ id: '', name: '', items: [] })
    }
    setEditDialogOpen(true)
  }

  const saveDict = async () => {
    setLoading(true)
    try {
      if (editIdx === null) {
        await dictionaryActions.createDictionary(editDraft.name, editDraft.items)
      } else {
        await dictionaryActions.updateDictionary(editDraft.id, editDraft.name, editDraft.items)
      }
      const data = await dictionaryActions.getDictionaries()
      setDicts(
        data.map((dict: any) => ({
          ...dict,
          items: Array.isArray(dict.items) ? dict.items : [],
        }))
      )
      setEditDialogOpen(false)
      setEditIdx(null)
      setEditDraft({ id: '', name: '', items: [] })
    } finally {
      setLoading(false)
    }
  }

  const deleteDict = async (idx: number) => {
    setLoading(true)
    try {
      await dictionaryActions.deleteDictionary(dicts[idx].id)
      const data = await dictionaryActions.getDictionaries()
      setDicts(
        data.map((dict: any) => ({
          ...dict,
          items: Array.isArray(dict.items) ? dict.items : [],
        }))
      )
    } finally {
      setLoading(false)
    }
  }

  return (
    <MainLayout>
      <Card className="p-6 max-w-3xl mx-auto">
        <h1 className="text-xl font-bold mb-4">Data Dictionary Management</h1>
        <Button onClick={() => openEdit()} className="mb-4">
          Add Dictionary
        </Button>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Name</TableHead>
              <TableHead>Items</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {dicts.map((dict, idx) => (
              <TableRow key={dict.id}>
                <TableCell>{dict.name}</TableCell>
                <TableCell>{dict.items?.length ?? 0} items</TableCell>
                <TableCell className="flex gap-2">
                  <Button size="sm" variant="outline" onClick={() => openEdit(idx)}>
                    Edit
                  </Button>
                  <Button size="icon" variant="ghost" onClick={() => deleteDict(idx)}>
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
        <Dialog open={editDialogOpen} onOpenChange={setEditDialogOpen}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>{editIdx === null ? 'Add Dictionary' : 'Edit Dictionary'}</DialogTitle>
              <DialogDescription>
                {editIdx === null
                  ? 'Enter the name and items for the new dictionary.'
                  : 'Manage the name and items for this dictionary.'}
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-2">
              <Input
                value={editDraft.name}
                onChange={(e) => setEditDraft({ ...editDraft, name: e.target.value })}
                placeholder="Name"
                className="text-xs"
              />
              <div className="border rounded p-2">
                <div className="font-semibold mb-2">Items</div>
                {editDraft.items.map((item, i) => (
                  <div key={i} className="flex gap-2 mb-1 items-center">
                    <Input
                      value={item.value}
                      onChange={(e) => {
                        const items = [...editDraft.items]
                        items[i] = { ...items[i], value: e.target.value }
                        setEditDraft({ ...editDraft, items })
                      }}
                      placeholder="Value"
                      className="text-xs "
                    />
                    <Input
                      value={item.label}
                      onChange={(e) => {
                        const items = [...editDraft.items]
                        items[i] = { ...items[i], label: e.target.value }
                        setEditDraft({ ...editDraft, items })
                      }}
                      placeholder="Label"
                      className="text-xs "
                    />
                    <Button
                      size="icon"
                      variant="ghost"
                      onClick={() => {
                        setEditDraft({
                          ...editDraft,
                          items: editDraft.items.filter((_, j) => j !== i),
                        })
                      }}
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                ))}
                <Button
                  size="sm"
                  variant="secondary"
                  className="text-xs mt-2"
                  onClick={() =>
                    setEditDraft({
                      ...editDraft,
                      items: [...editDraft.items, { value: '', label: '' }],
                    })
                  }
                >
                  Add Item
                </Button>
              </div>
            </div>
            <DialogFooter>
              <Button variant="secondary" onClick={() => setEditDialogOpen(false)}>
                Cancel
              </Button>
              <Button onClick={saveDict} disabled={loading}>
                Save
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </Card>
    </MainLayout>
  )
}
